### ISSUE TITLE
scroll and paginated, ReadiumCSS injection, "flash" when transition between spine items

### ISSUE THREAD

**Issue by danielweck** [edrlab/r2-navigator-js#20]
This latency/performance issue is mitigated in `r2-testapp-js` using a loader/spinner "blanking" screen to give the webview enough time to layout/render the page. In `readium-desktop` this functionality is not used, IIRC.
On mobile, the issue apparently does not exist at all, probably thanks to pre-rendering in adjacent webviews, and/or streamer-based ReadiumCSS injection?

**Comment by JayPanoz** [comment]
> On mobile, the issue apparently does not exist at all

Hmmmmm, we have that in the action items at some point, and Aferdita even checked whether injection was duplicated or not if I’m not mistaken. cc @HadrienGardeur

**Comment by llemeurfr** [comment]
In the desktop case it's not a repaint, it's that the text seems to appear without any CSS first (takes the whole screen width) then is immediately repainted with the CSS.

**Comment by JayPanoz** [comment]
Interesting. Had something similar in the webpub-viewer, which is not currently using ReadiumCSS. But in the webpub-viewer, styles are appended using JS after loading the doc. 

So I’m wondering whether it could be that CSS multicol is making two passes to layout/composite, as I’ve read in Chromium’s issue tracker a while ago.

**Comment by JayPanoz** [comment]
@danielweck I assume Chrome dev tools don’t report something like

```
[Violation] Forced reflow while executing JavaScript took 60ms
```

Right?

**Comment by danielweck** [comment]
Nope. It's something else. I'll run the Electron/Chromium profiler again.

**Comment by danielweck** [comment]
Fixed by injecting ReadiumCSS through streamer initially (HTML transform).
