### ISSUE TITLE
Add boolean user setting for TTS / read aloud sentence detection

### ISSUE THREAD

**Issue by danielweck** [edrlab/r2-navigator-js#26]
...there are publications ; such as Alice in Wonderland ; where the prose is interspersed with speech quotes, which tend to trip-up the sentence detection algorithm currently used in the TTS engine (as second pass after the DOM-based tokenization / text extraction routine). The resulting speech utterances are okay, but I imagine it would sound better if sentence splitting was disabled.

**Comment by danielweck** [comment]
A good test for large sections of text (which would normally result in far-too-long speech utterances, and therefore benefit from sentence detection) is Georgia:
https://idpf.github.io/epub3-samples/30/samples.html#georgia
https://github.com/IDPF/epub3-samples/tree/master/30/georgia-cfi

**Comment by danielweck** [comment]
Alice in Wonderland ... there are several variants, some of which use funky text layout and have lots of illustrations. In any case, the presence of speech quotations makes it hard for the sentence detection algorithm to figure out boundaries.

Test sources:

http://www.feedbooks.com/book/22/alice-s-adventures-in-wonderland

http://www.gutenberg.org/ebooks/28885

**Comment by danielweck** [comment]
PS: I tried several NLP (Natural Language Processing) approaches before settling on:
https://github.com/azu/sentence-splitter
(good balance between performance, ease of integration, and correctness with latin and japanese scripts)
(seems to work fine with arabic and hebrew ... but only looking at the visual result (I have no idea what the text says!))

**Comment by JayPanoz** [comment]
> some of which use funky text layout

Corner-case but SVG text on path (mentioning that because although rare, it is demoed in one sample file from a popular RS, please feel free to ping me if you want me to add this file in our test suite)

**Comment by danielweck** [comment]
I'm pretty sure SVG will trip-up the current TTS implementation, I haven't dared to try :)
