### ISSUE TITLE
Accessibility, screen reader support, Windows Narrator

### ISSUE THREAD

**Issue by danielweck** [edrlab/r2-navigator-js#37]
Interesting developments:
https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/master/UIA/i2i.md

...hopefully: first in Edge, then contributed shortly thereafter to Chromium core, then finally into a future Electron release.

CC @llemeurfr

**Comment by danielweck** [comment]
Related issue: 
https://github.com/readium/r2-testapp-js/issues/20#issuecomment-472526902

**Comment by JayPanoz** [comment]
Quick note: I’ve added `Edg` (so Chrome Edge or Chredge, `Edg` is how it presents itself in the UA string) to my browsers’ list for manual testing, and am paying particular attention to a11y so do not hesitate to ping me if I can help with testing that.
