### ISSUE TITLE
Electron protocol api changing

### ISSUE THREAD

**Issue by xVanTuring** [edrlab/r2-navigator-js#48]
https://github.com/readium/r2-navigator-js/blob/64c4533e4b2d08637a2841caf90a5c55fe97e38c/src/electron/main/sessions.ts#L178

`protocol.registerStandardSchemes` has been replaced  by`protocol.registerURLSchemeAsPrivileged` after v5.x

[latest doc](https://electronjs.org/docs/api/protocol#methods)

**Comment by danielweck** [comment]
Hello, thanks for chiming in!
Both `r2-navigator-js` and `r2-testapp-js` have had a "electron5" branch for several months, including all the necessary changes. I've just recently updated this preliminary work to fully support Electron 6, and the result has been merged into the `develop` branch(es).

`readium-desktop` has now also migrated to Electron 6 (was on v3).

Onwards and upwards! :)

**Comment by danielweck** [comment]
PS: the "electron5" has since been deleted, but I see you have a copy:
https://github.com/xVanTuring/r2-navigator-js/commits/feature/electron5

**Comment by xVanTuring** [comment]
Yes, I do notice the branch. 
Thanks for your effort, I will update my fork.  :)

By the way, I'm currently working on a viewer without  `webview-tag`, my idea is using iframe and  blob url, which was inspired by your previous work `readium-js-viewer`. 

And I noticed a [company](https://www.neat-reader.com/) is using your `readium-js` package, the result it produces is just copying all the epub body content into current html.

( By the way, it look like this company does not add any copyright info for your package)

**Comment by danielweck** [comment]
Thank you for the heads-up about https://www.neat-reader.com

The `readium-js-viewer` project is totally open-source under a permissive license, so people can use it as they wish :) (including all the subprojects `readium-js`, `readium-shared-js` and `readium-cfi-js`).

There are special licensing arrangements to use `readium-sdk` (the C++ Readium SDK, for native apps and with DRM support).

**Comment by danielweck** [comment]
Note that this project (`r2-navigator-js`) is really focused on Electron/Chromium integration, so this is not a direct replacement for `readium-js` / `readium-js-viewer` (which was very much focused on web / cloud reader, but is now a dormant / unmaintained project).

There is an effort to implement a successor to these old Readium projects, but this is still in infancy, there is not off-the-shelf software component right now (several companies are trying to work together to provide a common open-source codebase).

**Comment by danielweck** [comment]
The Electron `webview` tag is currently used because it provides additional control (e.g. security, scrip preloading) over the sandboxed iframe (which is a Chromium OutOfProcess iframe hosted by a custom component inside a shadow DOM).

Ideally, in a future revision of `r2-navigator-js` a regular DOM `iframe` will be used instead of `webview`, but this will require some refactoring, and finding different technical solutions to achieve the same functionality as we have now.

**Comment by danielweck** [comment]
The planned successor to the old `readium-js-viewer` + `readium-js` etc. Readium "web" components is https://github.com/readium/r2-navigator-web
Feel free to file issues / ask questions there, if you wish to learn more about project status.

There is also an active fork maintained by a core Readium contributor:
https://github.com/evidentpoint/r2-navigator-web

**Comment by xVanTuring** [comment]
That's a good news. I'll look into it.
