### ISSUE TITLE
Mixed NFD and NFC at misc/ReadiumCSS/ReadiumCSS-ebpaj_fonts_patch.css

### ISSUE THREAD

**Issue by toshiakikoike** [edrlab/r2-navigator-js#50]
misc/ReadiumCSS/ReadiumCSS-ebpaj_fonts_patch.css

It seems mixed NFD and NFC.
Line 44 and 74.
For example;
line 72, "ギ" is "U+30AE KATAKANA LETTER GI" and "ゴ" is "U+30B4 KATAKANA LETTER GO". 
But line 74, "ギ" is "キ"(U+30AD KATAKANA LETTER KI)+"゙"(U+3099 COMBINING KATAKANA-HIRAGANA VOICED SOUND MARK) and "ゴ" is "コ"(U+30B3 KATAKANA LETTER KO)+"゙"(U+3099 COMBINING KATAKANA-HIRAGANA VOICED SOUND MARK) 

I converted this file to NFC,
https://github.com/toshiakikoike/r2-navigator-js/blob/develop/misc/ReadiumCSS/ReadiumCSS-ebpaj_fonts_patch.css

(Sorry, I don't know how to pull request from out of project.)

**Comment by danielweck** [comment]
Hello, this is the ReadiumCSS source: https://github.com/readium/readium-css/tree/master/css/src

Could you please report in this repository?
Thank you!
