### ISSUE TITLE
'will-quit' can double trigger all listener in the host application | and why force to use app.quit ?

### ISSUE THREAD

**Issue by panaC** [edrlab/r2-navigator-js#51]
https://github.com/readium/r2-navigator-js/blob/d20357d964012f585e32f2f378ca3415433c3301/src/electron/main/sessions.ts#L913-L929

I don't think it's a good thing to catch event and to remove the function listener and then call the function linked to this event.

The host application should manage themself his lifecycle. The host should themself call the clearSession api.
I think r2-navigator should not be "clever".

A potential issue is to double trigger all listener in the host application. Instead the 'will-quit' event should be catch in the host app that call clearSession api from r2-navigator.

What do you think ?

**Comment by danielweck** [comment]
I agree.
Related comments: https://github.com/readium/readium-desktop/pull/1041#issuecomment-625167842

**Comment by danielweck** [comment]
Fixed:
https://github.com/readium/r2-navigator-js/blob/9b0c93b46e9c323fb7fc4e4eba6c0035038dbd3f/src/electron/main/sessions.ts#L914-L930
